use_frameworks!

platform :ios, '9.0'

target 'XQCSalarySignInWritingPad_Example' do
  pod 'XQCSalarySignInWritingPad', :path => '../'

  target 'XQCSalarySignInWritingPad_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
